# ===============================
# dev_signal_onspill-LH_1a.yaml
# ===============================

process:
  defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2025-000.root"
  cutset_name: "dev"
  max_workers: 4 
  verbosity: 1
  worker_verbosity: 0
  use_remote: true
  location: "tape"

postprocess:
  write_events: false 
  write_event_info: false 
  generated_events: 10000000 #196589320411 # Check with Natalie
  livetime: null 

output:
  out_path: "../output/results/dev_signal_onspill-LH_1a"
