# ===============================
# dev_signal_onspill-LH_aw.yaml
# ===============================

process:
  defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.root"
  cutset_name: "dev"
  max_workers: 75
  verbosity: 1
  worker_verbosity: 0
  use_remote: true  
  cuts_to_toggle: 
    one_track_per_event: false
    one_reco_electron: true

postprocess:
  write_events: false
  write_event_info: false
  generated_events: 4000000
  livetime: null

output:
  out_path: "../output/results/dev_signal_onspill-LH_aw_one_reco_electron"
