# ===============================
# dev_CRY_onspill-LH_1a.yaml
# ===============================

process:
  defname: "nts.mu2e.CosmicSignalOnSpillTriggered.MDC2025-000.root"
  cutset_name: "dev"
  max_workers: 44 
  verbosity: 1
  worker_verbosity: 0
  use_remote: true
  location: "tape"

postprocess:
  write_events: true
  write_event_info: true
  generated_events: 25000000000
  livetime: 10680000

output:
  out_path: "../output/results/dev_CRY_onspill-LH_1a"
