# ===============================
# dev_signal_mix2BB_onspill-LH_aw_noCRV.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointMix2BBTriggered.MDC2020aw_best_v1_3_v06_06_00.root"
    cutset_name: "dev"
    max_workers: 75
    verbosity: 1
    worker_verbosity: 0
    use_remote: true
    cuts_to_toggle: {"unvetoed" : False}


postprocess:
    write_events: true
    write_event_info: false
    generated_events: 4000000
    livetime: null

output:
    out_path: "../output/results/dev_signal_mix2BB_onspill-LH_aw_noCRV"