# ===============================
# SU2020b_CRY_onspill-LH_aw_noCRV.yaml
# ===============================

process:
    # defname: "nts.mu2e.CosmicCRYSignalAllMix2BBTriggered.MDC2020aw_best_v1_3_v06_05_00.root"
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.root"
    cutset_name: "SU2020b"
    max_workers: 50
    verbosity: 1
    worker_verbosity: 0
    cuts_to_toggle: {"unvetoed" : False}

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 41100000000
    livetime: 10680000

output:
    out_path: "../output/results/SU2020b_CRY_onspill-LH_aw_noCRV"