# ===============================
# SU2020b_signal_onspill-LH_aw.yaml
# ===============================

process:
    file_name: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/files/nts.mu2e.CeEndpointOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.001210_00000580.root"
    cutset_name: "SU2020b"
    use_remote: false
    # cuts_to_toggle:
    #     unvetoed: false

postprocess:
    write_events: false
    write_event_info: false
    generated_events: 4000
    veto: false
    livetime: null

output:
    out_path: "../output/results/SU2020b_signal_onspill-LH_aw_test"